# Generated by Django 4.2.3 on 2023-07-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type_1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
